ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CONSTRAINT ck_mark_mark_range CHECK (mark >= 1 AND mark <= 10), ALTER COLUMN student_id INT NOT NULL, ALTER COLUMN subject_id INT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT ck_subject_grade_range CHECK (grade >= 1 AND grade <= 5);
ALTER TABLE paymenttype ALTER COLUMN name VARCHAR(45) UNIQUE NOT NULL;
ALTER TABLE payment ALTER COLUMN type_id INT NOT NULL, ALTER COLUMN amount INT NOT NULL, ALTER COLUMN payment_date INT NOT NULL;