ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CONSTRAINT ck_mark_mark_range CHECK (mark BETWEEN 1 AND 10), ALTER COLUMN student_id BIGINT NOT NULL, ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT ck_subject_grade_range CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype ALTER COLUMN name VARCHAR(45) UNIQUE;
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL, ALTER COLUMN amount BIGINT NOT NULL, ALTER COLUMN payment_date BIGINT NOT NULL;