ALTER TABLE student MODIFY COLUMN birthday NOT NULL;
ALTER TABLE mark ADD CONSTRAINT ck_mark_mark_range CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT ck_subject_grade_range CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype MODIFY COLUMN name VARCHAR(45) UNIQUE;
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN date BIGINT NOT NULL;